# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assureBoundsCPP <- function(ind, g, lower, upper) {
    .Call(`_mogsa_assureBoundsCPP`, ind, g, lower, upper)
}

crossProductCPP <- function(ab, ac) {
    .Call(`_mogsa_crossProductCPP`, ab, ac)
}

computeVectorLengthCPP <- function(vec) {
    .Call(`_mogsa_computeVectorLengthCPP`, vec)
}

normalizeVectorCPP <- function(vec, prec) {
    .Call(`_mogsa_normalizeVectorCPP`, vec, prec)
}

#' @export
normalizeMatrixRowsCPP <- function(mat, prec) {
    .Call(`_mogsa_normalizeMatrixRowsCPP`, mat, prec)
}

computeAngleCPP <- function(vec1, vec2, prec) {
    .Call(`_mogsa_computeAngleCPP`, vec1, vec2, prec)
}

findNextCellCPP <- function(gradient) {
    .Call(`_mogsa_findNextCellCPP`, gradient)
}

convertIndices2CellIDCPP <- function(indices, dims) {
    .Call(`_mogsa_convertIndices2CellIDCPP`, indices, dims)
}

convertCellID2IndicesCPP <- function(cellID, dims) {
    .Call(`_mogsa_convertCellID2IndicesCPP`, cellID, dims)
}

#' @export
rotate90Right2D <- function(v) {
    .Call(`_mogsa_rotate90Right2D`, v)
}

#' @export
rotate90Left2D <- function(v) {
    .Call(`_mogsa_rotate90Left2D`, v)
}

#' @export
getMODescentRange2D <- function(a, b) {
    .Call(`_mogsa_getMODescentRange2D`, a, b)
}

#' @export
imputeBoundary <- function(moGradMat, gradMatList, dims) {
    .Call(`_mogsa_imputeBoundary`, moGradMat, gradMatList, dims)
}

#' @export
getCriticalPointsCellCPP <- function(moGradMat, gradMatList, div, lowerOrderCritical, dims, sinks_only) {
    .Call(`_mogsa_getCriticalPointsCellCPP`, moGradMat, gradMatList, div, lowerOrderCritical, dims, sinks_only)
}

#' @export
connectedComponentsGrid <- function(ids, dims) {
    .Call(`_mogsa_connectedComponentsGrid`, ids, dims)
}

#' @export
integrateVectorField <- function(gradMat, dims, sinks) {
    .Call(`_mogsa_integrateVectorField`, gradMat, dims, sinks)
}

#' @export
integrateBackwards <- function(gradMat, dims, startID, stopCells) {
    .Call(`_mogsa_integrateBackwards`, gradMat, dims, startID, stopCells)
}

#' @export
locallyNondominatedCPP <- function(fnMat, dims, includeDiagonals) {
    .Call(`_mogsa_locallyNondominatedCPP`, fnMat, dims, includeDiagonals)
}

#' @export
changeOfSignCPP <- function(fnVec, dims, includeDiagonals) {
    .Call(`_mogsa_changeOfSignCPP`, fnVec, dims, includeDiagonals)
}

#' @export
changeOfBasin <- function(basins, dims) {
    .Call(`_mogsa_changeOfBasin`, basins, dims)
}

gridBasedGradientCPP <- function(fnVec, dims, stepSizes, precNorm, precAngle) {
    .Call(`_mogsa_gridBasedGradientCPP`, fnVec, dims, stepSizes, precNorm, precAngle)
}

#' @export
hessian <- function(fnVec, dims, stepSizes) {
    .Call(`_mogsa_hessian`, fnVec, dims, stepSizes)
}

cumulateGradientsCPP <- function(centers, gradients, stopCells, precVectorLength, precNorm, fixDiagonals, cumulateGradientLength) {
    .Call(`_mogsa_cumulateGradientsCPP`, centers, gradients, stopCells, precVectorLength, precNorm, fixDiagonals, cumulateGradientLength)
}

getBiObjGradientCPP <- function(g1, g2, precNorm, precAngle) {
    .Call(`_mogsa_getBiObjGradientCPP`, g1, g2, precNorm, precAngle)
}

getTriObjGradientCPP <- function(g1, g2, g3, precNorm, precAngle) {
    .Call(`_mogsa_getTriObjGradientCPP`, g1, g2, g3, precNorm, precAngle)
}

getBiObjGradientGridCPP <- function(gradMat1, gradMat2, precNorm, precAngle) {
    .Call(`_mogsa_getBiObjGradientGridCPP`, gradMat1, gradMat2, precNorm, precAngle)
}

getTriObjGradientGridCPP <- function(gradMat1, gradMat2, gradMat3, precNorm, precAngle) {
    .Call(`_mogsa_getTriObjGradientGridCPP`, gradMat1, gradMat2, gradMat3, precNorm, precAngle)
}

calculateMaxDisplayHeightCPP <- function(heights, dims, includeDiagonals) {
    .Call(`_mogsa_calculateMaxDisplayHeightCPP`, heights, dims, includeDiagonals)
}

