# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assureBoundsCPP <- function(ind, g, lower, upper) {
    .Call(`_mogsa2_assureBoundsCPP`, ind, g, lower, upper)
}

computeVectorLengthCPP <- function(vec) {
    .Call(`_mogsa2_computeVectorLengthCPP`, vec)
}

normalizeVectorCPP <- function(vec, prec) {
    .Call(`_mogsa2_normalizeVectorCPP`, vec, prec)
}

computeAngleCPP <- function(vec1, vec2, prec) {
    .Call(`_mogsa2_computeAngleCPP`, vec1, vec2, prec)
}

findNextCellCPP <- function(angle) {
    .Call(`_mogsa2_findNextCellCPP`, angle)
}

convertIndices2CellIDCPP <- function(rowIndex, columnIndex, nRows = 100L, nColumns = 100L) {
    .Call(`_mogsa2_convertIndices2CellIDCPP`, rowIndex, columnIndex, nRows, nColumns)
}

convertCellID2IndicesCPP <- function(cellID, nRows = 100L, nColumns = 100L) {
    .Call(`_mogsa2_convertCellID2IndicesCPP`, cellID, nRows, nColumns)
}

cumulateGradientsCPP <- function(centers, gradients, precVectorLength, precNorm) {
    .Call(`_mogsa2_cumulateGradientsCPP`, centers, gradients, precVectorLength, precNorm)
}

